name = "DocumenterMarkdown"
uuid = "35a7dc56-b8c5-11e8-06a8-f7e9744e4a90"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
